
# DFIR IRIS Configuration
IRIS_CASE_ID = 1
IRIS_API_URL = "http[s]://{DFIR IRIS - IP OR DOMAIN}:{PORT}/"
IRIS_API_TOKEN = ""


# TIMESKETCH Configuration
TIMESKETCH_URL = "http[s]://{TIMESKETCH - IP OR DOMAIN}:{PORT}/"
TIMESKETCH_SKETCH_ID = 1
TIMESKETCH_MAX_EVENTS_RETRIEVED = 10000
TIMESKETCH_USERNAME = ""
TIMESKETCH_PASSWORD = ""

